/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAccediRouteImport } from './routes/_layout/accedi'
import { Route as LayoutCalendarioRouteImport } from './routes/_layout/calendario'
import { Route as LayoutFormula1RouteImport } from './routes/_layout/formula1'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutMotogpRouteImport } from './routes/_layout/motogp'
import { Route as LayoutPreferenzeRouteImport } from './routes/_layout/preferenze'
import { Route as LayoutReimpostaPasswordRouteImport } from './routes/_layout/reimposta-password'
import { Route as LayoutSinnerRouteImport } from './routes/_layout/sinner'
import { Route as LayoutStreamingRouteImport } from './routes/_layout/streaming'
import { Route as LayoutJuventusIndexRouteImport } from './routes/_layout/juventus.index'
import { Route as LayoutJuventusPartiteMatchIdRouteImport } from './routes/_layout/juventus.partite.$matchId'
import { Route as LayoutSquadraTeamSlugIndexRouteImport } from './routes/_layout/squadra.$teamSlug.index'
import { Route as LayoutSquadraTeamSlugPartiteMatchIdRouteImport } from './routes/_layout/squadra.$teamSlug.partite.$matchId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccediRoute = LayoutAccediRouteImport.update({
  id: '/accedi',
  path: '/accedi',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarioRoute = LayoutCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormula1Route = LayoutFormula1RouteImport.update({
  id: '/formula1',
  path: '/formula1',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMotogpRoute = LayoutMotogpRouteImport.update({
  id: '/motogp',
  path: '/motogp',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPreferenzeRoute = LayoutPreferenzeRouteImport.update({
  id: '/preferenze',
  path: '/preferenze',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReimpostaPasswordRoute = LayoutReimpostaPasswordRouteImport.update({
  id: '/reimposta-password',
  path: '/reimposta-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSinnerRoute = LayoutSinnerRouteImport.update({
  id: '/sinner',
  path: '/sinner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStreamingRoute = LayoutStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJuventusIndexRoute = LayoutJuventusIndexRouteImport.update({
  id: '/juventus/',
  path: '/juventus/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJuventusPartiteMatchIdRoute =
  LayoutJuventusPartiteMatchIdRouteImport.update({
    id: '/juventus/partite/$matchId',
    path: '/juventus/partite/$matchId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSquadraTeamSlugIndexRoute =
  LayoutSquadraTeamSlugIndexRouteImport.update({
    id: '/squadra/$teamSlug/',
    path: '/squadra/$teamSlug/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSquadraTeamSlugPartiteMatchIdRoute =
  LayoutSquadraTeamSlugPartiteMatchIdRouteImport.update({
    id: '/squadra/$teamSlug/partite/$matchId',
    path: '/squadra/$teamSlug/partite/$matchId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/accedi': typeof LayoutAccediRoute
  '/calendario': typeof LayoutCalendarioRoute
  '/formula1': typeof LayoutFormula1Route
  '/home': typeof LayoutHomeRoute
  '/motogp': typeof LayoutMotogpRoute
  '/preferenze': typeof LayoutPreferenzeRoute
  '/reimposta-password': typeof LayoutReimpostaPasswordRoute
  '/sinner': typeof LayoutSinnerRoute
  '/streaming': typeof LayoutStreamingRoute
  '/juventus/': typeof LayoutJuventusIndexRoute
  '/juventus/partite/$matchId': typeof LayoutJuventusPartiteMatchIdRoute
  '/squadra/$teamSlug/': typeof LayoutSquadraTeamSlugIndexRoute
  '/squadra/$teamSlug/partite/$matchId': typeof LayoutSquadraTeamSlugPartiteMatchIdRoute
}
export interface FileRoutesByTo {
  '/accedi': typeof LayoutAccediRoute
  '/calendario': typeof LayoutCalendarioRoute
  '/formula1': typeof LayoutFormula1Route
  '/home': typeof LayoutHomeRoute
  '/motogp': typeof LayoutMotogpRoute
  '/preferenze': typeof LayoutPreferenzeRoute
  '/reimposta-password': typeof LayoutReimpostaPasswordRoute
  '/sinner': typeof LayoutSinnerRoute
  '/streaming': typeof LayoutStreamingRoute
  '/': typeof LayoutIndexRoute
  '/juventus': typeof LayoutJuventusIndexRoute
  '/juventus/partite/$matchId': typeof LayoutJuventusPartiteMatchIdRoute
  '/squadra/$teamSlug': typeof LayoutSquadraTeamSlugIndexRoute
  '/squadra/$teamSlug/partite/$matchId': typeof LayoutSquadraTeamSlugPartiteMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/accedi': typeof LayoutAccediRoute
  '/_layout/calendario': typeof LayoutCalendarioRoute
  '/_layout/formula1': typeof LayoutFormula1Route
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/motogp': typeof LayoutMotogpRoute
  '/_layout/preferenze': typeof LayoutPreferenzeRoute
  '/_layout/reimposta-password': typeof LayoutReimpostaPasswordRoute
  '/_layout/sinner': typeof LayoutSinnerRoute
  '/_layout/streaming': typeof LayoutStreamingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/juventus/': typeof LayoutJuventusIndexRoute
  '/_layout/juventus/partite/$matchId': typeof LayoutJuventusPartiteMatchIdRoute
  '/_layout/squadra/$teamSlug/': typeof LayoutSquadraTeamSlugIndexRoute
  '/_layout/squadra/$teamSlug/partite/$matchId': typeof LayoutSquadraTeamSlugPartiteMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accedi'
    | '/calendario'
    | '/formula1'
    | '/home'
    | '/motogp'
    | '/preferenze'
    | '/reimposta-password'
    | '/sinner'
    | '/streaming'
    | '/juventus/'
    | '/juventus/partite/$matchId'
    | '/squadra/$teamSlug/'
    | '/squadra/$teamSlug/partite/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accedi'
    | '/calendario'
    | '/formula1'
    | '/home'
    | '/motogp'
    | '/preferenze'
    | '/reimposta-password'
    | '/sinner'
    | '/streaming'
    | '/'
    | '/juventus'
    | '/juventus/partite/$matchId'
    | '/squadra/$teamSlug'
    | '/squadra/$teamSlug/partite/$matchId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/accedi'
    | '/_layout/calendario'
    | '/_layout/formula1'
    | '/_layout/home'
    | '/_layout/motogp'
    | '/_layout/preferenze'
    | '/_layout/reimposta-password'
    | '/_layout/sinner'
    | '/_layout/streaming'
    | '/_layout/'
    | '/_layout/juventus/'
    | '/_layout/juventus/partite/$matchId'
    | '/_layout/squadra/$teamSlug/'
    | '/_layout/squadra/$teamSlug/partite/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accedi': {
      id: '/_layout/accedi'
      path: '/accedi'
      fullPath: '/accedi'
      preLoaderRoute: typeof LayoutAccediRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendario': {
      id: '/_layout/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof LayoutCalendarioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/formula1': {
      id: '/_layout/formula1'
      path: '/formula1'
      fullPath: '/formula1'
      preLoaderRoute: typeof LayoutFormula1RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/motogp': {
      id: '/_layout/motogp'
      path: '/motogp'
      fullPath: '/motogp'
      preLoaderRoute: typeof LayoutMotogpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/preferenze': {
      id: '/_layout/preferenze'
      path: '/preferenze'
      fullPath: '/preferenze'
      preLoaderRoute: typeof LayoutPreferenzeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reimposta-password': {
      id: '/_layout/reimposta-password'
      path: '/reimposta-password'
      fullPath: '/reimposta-password'
      preLoaderRoute: typeof LayoutReimpostaPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sinner': {
      id: '/_layout/sinner'
      path: '/sinner'
      fullPath: '/sinner'
      preLoaderRoute: typeof LayoutSinnerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/streaming': {
      id: '/_layout/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof LayoutStreamingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/juventus/': {
      id: '/_layout/juventus/'
      path: '/juventus'
      fullPath: '/juventus/'
      preLoaderRoute: typeof LayoutJuventusIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/juventus/partite/$matchId': {
      id: '/_layout/juventus/partite/$matchId'
      path: '/juventus/partite/$matchId'
      fullPath: '/juventus/partite/$matchId'
      preLoaderRoute: typeof LayoutJuventusPartiteMatchIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/squadra/$teamSlug/': {
      id: '/_layout/squadra/$teamSlug/'
      path: '/squadra/$teamSlug'
      fullPath: '/squadra/$teamSlug/'
      preLoaderRoute: typeof LayoutSquadraTeamSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/squadra/$teamSlug/partite/$matchId': {
      id: '/_layout/squadra/$teamSlug/partite/$matchId'
      path: '/squadra/$teamSlug/partite/$matchId'
      fullPath: '/squadra/$teamSlug/partite/$matchId'
      preLoaderRoute: typeof LayoutSquadraTeamSlugPartiteMatchIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccediRoute: typeof LayoutAccediRoute
  LayoutCalendarioRoute: typeof LayoutCalendarioRoute
  LayoutFormula1Route: typeof LayoutFormula1Route
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutMotogpRoute: typeof LayoutMotogpRoute
  LayoutPreferenzeRoute: typeof LayoutPreferenzeRoute
  LayoutReimpostaPasswordRoute: typeof LayoutReimpostaPasswordRoute
  LayoutSinnerRoute: typeof LayoutSinnerRoute
  LayoutStreamingRoute: typeof LayoutStreamingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutJuventusIndexRoute: typeof LayoutJuventusIndexRoute
  LayoutJuventusPartiteMatchIdRoute: typeof LayoutJuventusPartiteMatchIdRoute
  LayoutSquadraTeamSlugIndexRoute: typeof LayoutSquadraTeamSlugIndexRoute
  LayoutSquadraTeamSlugPartiteMatchIdRoute: typeof LayoutSquadraTeamSlugPartiteMatchIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccediRoute: LayoutAccediRoute,
  LayoutCalendarioRoute: LayoutCalendarioRoute,
  LayoutFormula1Route: LayoutFormula1Route,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutMotogpRoute: LayoutMotogpRoute,
  LayoutPreferenzeRoute: LayoutPreferenzeRoute,
  LayoutReimpostaPasswordRoute: LayoutReimpostaPasswordRoute,
  LayoutSinnerRoute: LayoutSinnerRoute,
  LayoutStreamingRoute: LayoutStreamingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutJuventusIndexRoute: LayoutJuventusIndexRoute,
  LayoutJuventusPartiteMatchIdRoute: LayoutJuventusPartiteMatchIdRoute,
  LayoutSquadraTeamSlugIndexRoute: LayoutSquadraTeamSlugIndexRoute,
  LayoutSquadraTeamSlugPartiteMatchIdRoute:
    LayoutSquadraTeamSlugPartiteMatchIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
