-- NON FA NIENTE, DI PROPOSITO. Leggere prima di riprovarci.
--
-- Questo file esisteva per togliere ad `anon` e `authenticated` l'accesso alle
-- funzioni di `pg_net`. Applicandolo davvero, il 31 agosto 2026, si e' scoperto
-- che **non e' possibile farlo da qui**, e che riprovarci in altre forme e'
-- peggio che lasciar stare. Il file resta come nota, perche' cancellarlo
-- significherebbe che qualcuno riscrivera' la stessa migration fra sei mesi.
--
-- ===========================================================================
-- PRIMO MOTIVO: il REVOKE non fallisce, semplicemente non fa niente
-- ===========================================================================
-- Le dodici funzioni di pg_net e lo schema `net` appartengono a
-- `supabase_admin`. Le migration girano come `postgres`, che **non e'
-- superuser e non e' membro di `supabase_admin`** (verificato con
-- `pg_has_role`). In PostgreSQL un REVOKE eseguito da chi non e' owner ne' ha
-- GRANT OPTION emette un warning e prosegue: nessun errore, nessun effetto.
--
-- E' il modo peggiore in cui una migration puo' sbagliare. Applicata, sembra
-- riuscita: il file finisce nella cartella, il changelog dichiara il problema
-- chiuso, e il privilegio e' esattamente dov'era. Lo si vede solo rileggendo i
-- privilegi dopo, che e' quello che e' stato fatto.
--
-- ===========================================================================
-- SECONDO MOTIVO: la revoca giusta fermerebbe le notifiche
-- ===========================================================================
-- L'ACL reale di `net.http_post` e' `=X/supabase_admin`, dove il grantee vuoto
-- prima di `=` significa **PUBLIC**. `anon` non ha nessun grant diretto: eredita
-- da PUBLIC. Quindi la revoca corretta sarebbe `FROM PUBLIC`, non `FROM anon`.
--
-- Ma nella stessa ACL non compare `postgres`, ed e' `postgres` a far girare il
-- job cron del dispatcher. `postgres` puo' chiamare `net.http_post` **solo**
-- tramite PUBLIC. Revocare da PUBLIC senza prima concedere esplicitamente a
-- `postgres` fermerebbe le notifiche push - e anche quel GRANT richiede di
-- essere owner, cioe' `supabase_admin`.
--
-- ===========================================================================
-- QUANTO E' GRAVE DAVVERO: misurato, non supposto
-- ===========================================================================
-- Verificato dall'esterno il 31 agosto 2026, con la anon key pubblica:
--
--   POST /rest/v1/rpc/http_post              -> 404
--   ... con Accept-Profile: net              -> PGRST106
--      "Only the following schemas are exposed: public, graphql_public"
--
-- PostgREST espone `public` e `graphql_public`. Lo schema `net` non e'
-- raggiungibile dall'API, e lo schema `public` non contiene **nessuna**
-- funzione da cui rimbalzare. Il privilegio c'e' e non ha una porta.
--
-- Resta difesa in profondita' mancante, non un buco aperto: diventerebbe
-- sfruttabile solo se qualcuno creasse una funzione `SECURITY DEFINER` in
-- `public` che chiama `net.*`, o se gli schemi esposti cambiassero.
--
-- ===========================================================================
-- COSA FARE, SE UN GIORNO SERVE
-- ===========================================================================
-- Chiedere a Supabase: serve `supabase_admin`, che i progetti non hanno. In
-- alternativa, e con lo stesso effetto pratico, tenere `public` senza funzioni
-- e non aggiungere schemi esposti - due cose che si verificano da qui e che il
-- ROADMAP tiene sotto controllo.
